name: EpicBingo
version: 1.0
main: com.gmail.justbru00.epic.bingo.main.EpicBingoMain
api-version: 1.14
commands:
  game:
    description: Allows the bingo game to be managed.
  bingocard:
    description: Opens the bingo card GUI.
    aliases: [bingo,card]
  